### ISSUE TITLE
ios Runner failed

### ISSUE THREAD

**Issue by chubzchoc** [geordyvcErasmus/flutter_sms#5]
**Describe the bug**
I develop multi platform app. 
I know that this plugin only works in Android. 
But, when I run my app in iOS, it give me error.

**To Reproduce**
1. do Pod Install
2. error message : [!] No podspec found for `sms_maintained` in `.symlinks/plugins/sms_maintained/ios`

**Expected behavior**
I can run my app both in Android and iOS. 

is there any setup to make my app can running in iOS ? 
or how to specified this plugin to installed in Android only ? 
Thanks

**Comment by chubzchoc** [comment]
i've fixed this issue by modifying sms_maintained in my ios folder

**Comment by KingIdee** [comment]
Modified it to what?

**Comment by sssalib42** [comment]
The fine print says that this library is only available for Android!!!

Apple will not let any app, aside from the native messaging app to send out messages.
They are too serious about spam.

**Comment by gpibarra** [comment]
The error does not say that you want to use it on iphone. But by adding the library (for use only on Android) it does not work on iphone when running "pod install".
You have to rename the file "ios / sms.podspec" to "ios / sms_maintained.podspec" and the contents of that file, line 5 "s.name" change "sms" to "sms_maintained"
